### PR TITLE
Added polish to language_gear.lua 70% done.

### PR DESCRIPTION
**Pull request by KaSkA3eR**
I done 70% of translation of gear but please can someone tell me how can i change language to polish in my dayz?

### CODE REVIEW

**Comment by 0xCiBeR** [comment]
You should fully translate it for us to merge it into master.

**Comment by KaSkA3eR** [comment]
Okay when i complete it i will put again, how can i change language on server?

**Comment by mtadayz** [comment]
Server? You can't change the language serverwide, it's client only (obviously, why would I want to play on a server whose language I don't understand?). 

Go to ui_gear.lua and search for this:

checkTheLanguage()

Add this:

elseif languageCode == "pl" then
        languageCode = "pl"

before the else clause.

Next, go to languageTable and add "pl" as an entry. There, you just added polish as a language. But in all honesty, before you can even think about doing something like that, why don't you check the code yourself first before you ask? Most stuff can easily be solved by just SEARCHING.

**Comment by KaSkA3eR** [comment]
I added this to ui_gear.lua but when I run server i can't open any Gear so I think it can be issue of language_gear.lua.

**Comment by KaSkA3eR** [comment]
I changed these values on language_gear
ItemType
Description
TranslationOfItem
itemAction

**Comment by KaSkA3eR** [comment]
Sorry I'm new at LUA :/
I know where i made mistake. It's obvious xD
Sorry for waste your time...
["Żywność"] = { i didn't changed this :-1: 
:+1: Thanks for help I will try to help DayZ community as my best

**Pull request closed without merging**
