### PR TITLE
Bugfix / Update / Delete

### PR DESCRIPTION
**Pull request by imCEASER**
Bugfixed this files:
- handlers/world/client/night/c_night.lua
- handlers/players/client/flashlight/c_shader_light.lua
- handlers/world/client/sky/c_main.lua
- handlers/world/client/tree_chop.lua
- handlers/world/client/chat.lua
- tools/sidenotifications/jq_client.lua
- models/loadskins.lua
- gui/journal/journal.lua
- gui/gear/sidemenu_gear.lua
- gui/scoreboard/scoreboard.lua
- gui/gear/ui_gear.lua
- gui/gear/hud_gear.lua
- handlers/players/client/status_player.lua
- handlers/players/client/damage_player.lua
- gui/status/player_status.lua

Updated and deleted lines in this file:
- addons.lua

### CODE REVIEW

**Comment by 0xCiBeR** [comment]
Can you detail what bug fixes did you do? Also preform a clean pull request as it's conflicting with master and we can not merge it.

**Comment by imCEASER** [comment]
It basically someone rename the folder 'DayZ' to eg 'MTA: DayZ' scripts will mistake for trying to pull a folder called 'DayZ' (non-existent)

I did not understand because it is failing to make the change ...

**Comment by neves768** [comment]
I'ill try to explain it:
He removed all the ":DayZ/" (from static folder to relative folder) and changed the event handler of the Debug Monitor (onClientRender) to a timer with 1second

**Comment by imCEASER** [comment]
@neves768, in fact, remove only the ":DayZ/"

**Pull request closed without merging**
