### PR TITLE
Changed itemAction in Polish Language

### PR DESCRIPTION
**Pull request by KaSkA3eR**
I also added tip for translators to don't translate itemAction
It works for me when I translated it but L told me that I need to change this to English so I did it.

### CODE REVIEW

**Comment by Renkon** [comment]
That's an issue we have to take into consideration. Although fixed, sooner
or later we'll have to think about changing the way we call elements to
prevent issues like this.

2015-09-21 15:09 GMT-03:00 L notifications@github.com:

**Comment by KaSkA3eR** [comment]
But I see when I translated itemAction when i rightclick item i see something like this: Equip Flashlight, Equip G36C etc

**Comment by mtadayz** [comment]
So? You made a pull request to a gamemode that is available for everyone, so you have to use a language that is being used by said gamemode as a whole: ENGLISH. If the gamemode was in german, you'd have to write arrays in german, if it was in russian, ditto. That way, we avoid confusion. Deal with it.

**Comment by KaSkA3eR** [comment]
I know that but it's only my opinon :).
BTW I have question, I want to make configurable respawn time, I made variable in cfgserver
gameplayVariables["respawntime"] = 20
I use it like this:
"You died! \nYou will respawn in " .. gameplayVariables["respawntime"] .. " seconds."
But I got this error:
attempt to concatenate field 'respawntime' (a nil value)
What can made this error?

**Comment by mtadayz** [comment]
That message is clientsided, so your variable has to be in cfgClient.

**Pull request merged**
