### PR TITLE
Added Polish Language

### PR DESCRIPTION
**Pull request by KaSkA3eR**
Added Polish Language, 100% completed.

### CODE REVIEW

**Comment by 0xCiBeR** [comment]
Is this tested?

**Comment by KaSkA3eR** [comment]
Yes,  i tested and it works good.

**Comment by mtadayz** [comment]
Really? Because you nitwit translated the internal array names for actions too ("Equip Primary Weapon", "Use", "Pitch a tent", ...), which means you won't be able to use any items AT ALL. Please change that.

**Comment by KaSkA3eR** [comment]
okay i will edit this and resend again :)

**Pull request merged**
