### PR TITLE
Anti-teleport detection [BattlDayZ]

### PR DESCRIPTION
**Pull request by neves768**
Added anti-teleport detection method to BattlDayZ

### CODE REVIEW

**Comment by 0xCiBeR** [comment]
Is this confirmed to work?

**Comment by neves768** [comment]
yes, it was tested (admin isn't banned, only users)
But the user can get a ban if a admin teleport him to somewhere (we need to edit the Admin panel resource to avoid this ban or try to check if he was teleported by admin)...

**Comment by 0xCiBeR** [comment]
OK, I'll or some other developer will check this ASAP to merge it or not.

**Comment by 0xCiBeR** [comment]
Waiting for proper feedback on this one.

**Pull request merged**
